apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: kiosk-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kiosk-backend
  template:
    metadata:
      labels:
        app: kiosk-backend
    spec:
      containers:
        - name: kiosk-backend
          image: my-docker-repo/kiosk-back:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "{{ .Values.db.url }}"
            - name: DB_USERNAME
              value: "{{ .Values.db.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.db.password }}"
            - name: JWT_SECRET_KEY
              value: "{{ .Values.jwt.secretKey }}"
            - name: AWS_ACCESS_KEY
              value: "{{ .Values.aws.accessKey }}"
            - name: AWS_SECRET_KEY
              value: "{{ .Values.aws.secretKey }}"
