apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: kiosk-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kiosk-backend
  template:
    metadata:
      labels:
        app: kiosk-backend
    spec:
      containers:
        - name: kiosk-backend
          image: my-docker-repo/kiosk-back:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: ${DB_URL}
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: JWT_ISSUER
              value: ${JWT_ISSUER}
            - name: JWT_SECRET_KEY
              value: ${JWT_SECRET_KEY}
            - name: IAP_API_KEY
              value: ${IAP_API_KEY}
            - name: IAP_SECRET_KEY
              value: ${IAP_SECRET_KEY}
            - name: AWS_ACCESS_KEY
              value: ${AWS_ACCESS_KEY}
            - name: AWS_SECRET_KEY
              value: ${AWS_SECRET_KEY}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/teak-formula-414404-60aed70b9172.json"
          volumeMounts:
            - name: gcp-key-volume
              mountPath: /etc/teak-formula-414404-60aed70b9172.json
              subPath: teak-formula-414404-60aed70b9172.json
      volumes:
        - name: gcp-key-volume
          secret:
            secretName: gcp-key-secret
