apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: {{ .Values.db.url }}
            - name: DB_USERNAME
              value: {{ .Values.db.username }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}
            - name: JWT_ISSUER
              value: {{ .Values.jwt.issuer }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.jwt.secretKey }}
            - name: IAP_API_KEY
              value: {{ .Values.iap.apiKey }}
            - name: IAP_SECRET_KEY
              value: {{ .Values.iap.secretKey }}
            - name: AWS_ACCESS_KEY
              value: {{ .Values.aws.accessKey }}
            - name: AWS_SECRET_KEY
              value: {{ .Values.aws.secretKey }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/teak-formula-414404-60aed70b9172.json"
          volumeMounts:
            - name: gcp-key-volume
              mountPath: /etc/teak-formula-414404-60aed70b9172.json
              subPath: teak-formula-414404-60aed70b9172.json
      volumes:
        - name: gcp-key-volume
          secret:
            secretName: gcp-key-secret
